// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/currency-conversion.proto

package mastercard

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MastercardCurrencyConversionRequest struct {
	// Date of the requested FX rates.
	FxDate string `protobuf:"bytes,1,opt,name=fxDate,proto3" json:"fxDate,omitempty"`
	// Currency of the transaction.
	TransCurr string `protobuf:"bytes,2,opt,name=transCurr,proto3" json:"transCurr,omitempty"`
	// Cardholder billing currency.
	CrdhldBillCurr string `protobuf:"bytes,3,opt,name=crdhldBillCurr,proto3" json:"crdhldBillCurr,omitempty"`
	// Additional fees imposed by the bank.
	BankFee int64 `protobuf:"varint,4,opt,name=bankFee,proto3" json:"bankFee,omitempty"`
	// Amount in the transaction currency
	TransAmt             float32  `protobuf:"fixed32,5,opt,name=transAmt,proto3" json:"transAmt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MastercardCurrencyConversionRequest) Reset()         { *m = MastercardCurrencyConversionRequest{} }
func (m *MastercardCurrencyConversionRequest) String() string { return proto.CompactTextString(m) }
func (*MastercardCurrencyConversionRequest) ProtoMessage()    {}
func (*MastercardCurrencyConversionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1d46281ede0b93f, []int{0}
}

func (m *MastercardCurrencyConversionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MastercardCurrencyConversionRequest.Unmarshal(m, b)
}
func (m *MastercardCurrencyConversionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MastercardCurrencyConversionRequest.Marshal(b, m, deterministic)
}
func (m *MastercardCurrencyConversionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MastercardCurrencyConversionRequest.Merge(m, src)
}
func (m *MastercardCurrencyConversionRequest) XXX_Size() int {
	return xxx_messageInfo_MastercardCurrencyConversionRequest.Size(m)
}
func (m *MastercardCurrencyConversionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MastercardCurrencyConversionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MastercardCurrencyConversionRequest proto.InternalMessageInfo

func (m *MastercardCurrencyConversionRequest) GetFxDate() string {
	if m != nil {
		return m.FxDate
	}
	return ""
}

func (m *MastercardCurrencyConversionRequest) GetTransCurr() string {
	if m != nil {
		return m.TransCurr
	}
	return ""
}

func (m *MastercardCurrencyConversionRequest) GetCrdhldBillCurr() string {
	if m != nil {
		return m.CrdhldBillCurr
	}
	return ""
}

func (m *MastercardCurrencyConversionRequest) GetBankFee() int64 {
	if m != nil {
		return m.BankFee
	}
	return 0
}

func (m *MastercardCurrencyConversionRequest) GetTransAmt() float32 {
	if m != nil {
		return m.TransAmt
	}
	return 0
}

type MastercardCurrencyConversionReply struct {
	Response             *CurrencyResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MastercardCurrencyConversionReply) Reset()         { *m = MastercardCurrencyConversionReply{} }
func (m *MastercardCurrencyConversionReply) String() string { return proto.CompactTextString(m) }
func (*MastercardCurrencyConversionReply) ProtoMessage()    {}
func (*MastercardCurrencyConversionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1d46281ede0b93f, []int{1}
}

func (m *MastercardCurrencyConversionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MastercardCurrencyConversionReply.Unmarshal(m, b)
}
func (m *MastercardCurrencyConversionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MastercardCurrencyConversionReply.Marshal(b, m, deterministic)
}
func (m *MastercardCurrencyConversionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MastercardCurrencyConversionReply.Merge(m, src)
}
func (m *MastercardCurrencyConversionReply) XXX_Size() int {
	return xxx_messageInfo_MastercardCurrencyConversionReply.Size(m)
}
func (m *MastercardCurrencyConversionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MastercardCurrencyConversionReply.DiscardUnknown(m)
}

var xxx_messageInfo_MastercardCurrencyConversionReply proto.InternalMessageInfo

func (m *MastercardCurrencyConversionReply) GetResponse() *CurrencyResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

type CurrencyResponse struct {
	// The name of the service being requested.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The type of response being returned by the API.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// The description of the API being called.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Additional fees imposed by the bank.
	Date *timestamp.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	// Amount in the transaction currency
	TransAmt float32 `protobuf:"fixed32,5,opt,name=transAmt,proto3" json:"transAmt,omitempty"`
	// Data
	Data                 *CurrencyDataResponse `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CurrencyResponse) Reset()         { *m = CurrencyResponse{} }
func (m *CurrencyResponse) String() string { return proto.CompactTextString(m) }
func (*CurrencyResponse) ProtoMessage()    {}
func (*CurrencyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1d46281ede0b93f, []int{2}
}

func (m *CurrencyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrencyResponse.Unmarshal(m, b)
}
func (m *CurrencyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrencyResponse.Marshal(b, m, deterministic)
}
func (m *CurrencyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrencyResponse.Merge(m, src)
}
func (m *CurrencyResponse) XXX_Size() int {
	return xxx_messageInfo_CurrencyResponse.Size(m)
}
func (m *CurrencyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrencyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CurrencyResponse proto.InternalMessageInfo

func (m *CurrencyResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CurrencyResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CurrencyResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CurrencyResponse) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *CurrencyResponse) GetTransAmt() float32 {
	if m != nil {
		return m.TransAmt
	}
	return 0
}

func (m *CurrencyResponse) GetData() *CurrencyDataResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

type CurrencyDataResponse struct {
	// Rate applied to the transaction to convert from Transaction Currency to Cardholder Billing Currency.
	ConversionRate float32 `protobuf:"fixed32,1,opt,name=conversionRate,proto3" json:"conversionRate,omitempty"`
	// Amount in the cardholder billing currency.
	CrdhldBillAmt float32 `protobuf:"fixed32,2,opt,name=crdhldBillAmt,proto3" json:"crdhldBillAmt,omitempty"`
	// Amount in the transaction currency.
	TransAmt float32 `protobuf:"fixed32,3,opt,name=transAmt,proto3" json:"transAmt,omitempty"`
	// Date of the requested FX rates.
	FxDate string `protobuf:"bytes,4,opt,name=fxDate,proto3" json:"fxDate,omitempty"`
	// Currency of the transaction
	TransCurr string `protobuf:"bytes,5,opt,name=transCurr,proto3" json:"transCurr,omitempty"`
	// Cardholder billing currency.
	CrdhldBillCurr string `protobuf:"bytes,6,opt,name=crdhldBillCurr,proto3" json:"crdhldBillCurr,omitempty"`
	// Bankfee
	BankFee float32 `protobuf:"fixed32,7,opt,name=bankFee,proto3" json:"bankFee,omitempty"`
	// Error code
	ErrorCode int64 `protobuf:"varint,8,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	// The reason for the error.
	ErrorMessage         string   `protobuf:"bytes,9,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrencyDataResponse) Reset()         { *m = CurrencyDataResponse{} }
func (m *CurrencyDataResponse) String() string { return proto.CompactTextString(m) }
func (*CurrencyDataResponse) ProtoMessage()    {}
func (*CurrencyDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1d46281ede0b93f, []int{3}
}

func (m *CurrencyDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrencyDataResponse.Unmarshal(m, b)
}
func (m *CurrencyDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrencyDataResponse.Marshal(b, m, deterministic)
}
func (m *CurrencyDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrencyDataResponse.Merge(m, src)
}
func (m *CurrencyDataResponse) XXX_Size() int {
	return xxx_messageInfo_CurrencyDataResponse.Size(m)
}
func (m *CurrencyDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrencyDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CurrencyDataResponse proto.InternalMessageInfo

func (m *CurrencyDataResponse) GetConversionRate() float32 {
	if m != nil {
		return m.ConversionRate
	}
	return 0
}

func (m *CurrencyDataResponse) GetCrdhldBillAmt() float32 {
	if m != nil {
		return m.CrdhldBillAmt
	}
	return 0
}

func (m *CurrencyDataResponse) GetTransAmt() float32 {
	if m != nil {
		return m.TransAmt
	}
	return 0
}

func (m *CurrencyDataResponse) GetFxDate() string {
	if m != nil {
		return m.FxDate
	}
	return ""
}

func (m *CurrencyDataResponse) GetTransCurr() string {
	if m != nil {
		return m.TransCurr
	}
	return ""
}

func (m *CurrencyDataResponse) GetCrdhldBillCurr() string {
	if m != nil {
		return m.CrdhldBillCurr
	}
	return ""
}

func (m *CurrencyDataResponse) GetBankFee() float32 {
	if m != nil {
		return m.BankFee
	}
	return 0
}

func (m *CurrencyDataResponse) GetErrorCode() int64 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *CurrencyDataResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*MastercardCurrencyConversionRequest)(nil), "mastercard.MastercardCurrencyConversionRequest")
	proto.RegisterType((*MastercardCurrencyConversionReply)(nil), "mastercard.MastercardCurrencyConversionReply")
	proto.RegisterType((*CurrencyResponse)(nil), "mastercard.CurrencyResponse")
	proto.RegisterType((*CurrencyDataResponse)(nil), "mastercard.CurrencyDataResponse")
}

func init() { proto.RegisterFile("pb/currency-conversion.proto", fileDescriptor_f1d46281ede0b93f) }

var fileDescriptor_f1d46281ede0b93f = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x8e, 0x9b, 0x26, 0x53, 0x40, 0x68, 0x04, 0xc8, 0x44, 0x91, 0x30, 0x06, 0xa1, 0x5c,
	0xea, 0x48, 0x85, 0x03, 0x57, 0x48, 0x05, 0xa7, 0x5e, 0x0c, 0x57, 0x0e, 0x1b, 0x7b, 0x1a, 0x2c,
	0xec, 0xdd, 0x65, 0x77, 0x53, 0xe1, 0x17, 0xe1, 0x5d, 0xe0, 0x61, 0x78, 0x16, 0x94, 0x89, 0x7f,
	0x9a, 0xb4, 0xb4, 0xbd, 0xed, 0x7c, 0xf3, 0xcd, 0x78, 0x66, 0xbe, 0xcf, 0x30, 0xd5, 0xcb, 0x79,
	0xb6, 0x36, 0x86, 0x64, 0x56, 0x1f, 0x67, 0x4a, 0x5e, 0x90, 0xb1, 0x85, 0x92, 0x89, 0x36, 0xca,
	0x29, 0x84, 0x4a, 0x58, 0x47, 0x26, 0x13, 0x26, 0x9f, 0x3c, 0x5f, 0x29, 0xb5, 0x2a, 0x69, 0xce,
	0x99, 0xe5, 0xfa, 0x7c, 0xee, 0x8a, 0x8a, 0xac, 0x13, 0x95, 0xde, 0x92, 0xe3, 0xdf, 0x1e, 0xbc,
	0x3c, 0xeb, 0xf8, 0x8b, 0xa6, 0xe9, 0xa2, 0xeb, 0x99, 0xd2, 0x8f, 0x35, 0x59, 0x87, 0x4f, 0x61,
	0x78, 0xfe, 0xf3, 0x54, 0x38, 0x0a, 0xbd, 0xc8, 0x9b, 0x8d, 0xd3, 0x26, 0xc2, 0x29, 0x8c, 0x9d,
	0x11, 0xd2, 0x6e, 0x2a, 0x43, 0x9f, 0x53, 0x3d, 0x80, 0xaf, 0xe1, 0x61, 0x66, 0xf2, 0x6f, 0x65,
	0xfe, 0xa1, 0x28, 0x4b, 0xa6, 0x0c, 0x98, 0xb2, 0x87, 0x62, 0x08, 0x87, 0x4b, 0x21, 0xbf, 0x7f,
	0x24, 0x0a, 0x83, 0xc8, 0x9b, 0x0d, 0xd2, 0x36, 0xc4, 0x09, 0x8c, 0xb8, 0xdd, 0xfb, 0xca, 0x85,
	0x07, 0x91, 0x37, 0xf3, 0xd3, 0x2e, 0x8e, 0xbf, 0xc2, 0x8b, 0x9b, 0x47, 0xd7, 0x65, 0x8d, 0xef,
	0x60, 0x64, 0xc8, 0x6a, 0x25, 0xed, 0x76, 0xf4, 0xa3, 0x93, 0x69, 0xd2, 0x1f, 0x28, 0x69, 0xcb,
	0xd2, 0x86, 0x93, 0x76, 0xec, 0xf8, 0xaf, 0x07, 0x8f, 0xf6, 0xd3, 0x88, 0x10, 0x48, 0x51, 0xb5,
	0x57, 0xe0, 0xf7, 0x06, 0x73, 0xb5, 0xa6, 0x66, 0x7d, 0x7e, 0x63, 0x04, 0x47, 0x39, 0xd9, 0xcc,
	0x14, 0xda, 0x15, 0x4a, 0x36, 0x6b, 0x5f, 0x86, 0x30, 0x81, 0x20, 0xdf, 0xdc, 0x33, 0xe0, 0xa1,
	0x26, 0xc9, 0x56, 0xa9, 0xa4, 0x55, 0x2a, 0xf9, 0xd2, 0x2a, 0x95, 0x32, 0xef, 0xa6, 0x4b, 0xe0,
	0x5b, 0xee, 0x25, 0xc2, 0x21, 0xf7, 0x8a, 0xae, 0x5b, 0xf0, 0x54, 0x38, 0xd1, 0x2d, 0xc9, 0xec,
	0xf8, 0x8f, 0x0f, 0x8f, 0xaf, 0x4b, 0xb3, 0x6c, 0xfd, 0x19, 0x5b, 0xd1, 0xfd, 0x74, 0x0f, 0xc5,
	0x57, 0xf0, 0xa0, 0x17, 0x72, 0x33, 0x97, 0xcf, 0xb4, 0x5d, 0x70, 0x67, 0xf0, 0xc1, 0xde, 0xe0,
	0xbd, 0xad, 0x82, 0xff, 0xdb, 0xea, 0xe0, 0x76, 0x5b, 0x0d, 0x6f, 0xb3, 0xd5, 0x21, 0x7f, 0xb8,
	0xb3, 0xd5, 0x14, 0xc6, 0x64, 0x8c, 0x32, 0x0b, 0x95, 0x53, 0x38, 0x62, 0xcb, 0xf5, 0x00, 0xc6,
	0x70, 0x9f, 0x83, 0x33, 0xb2, 0x56, 0xac, 0x28, 0x1c, 0x73, 0xf7, 0x1d, 0xec, 0xe4, 0x97, 0x07,
	0xcf, 0xae, 0xba, 0xef, 0x33, 0x99, 0x8b, 0x22, 0x23, 0xac, 0xe1, 0xc9, 0x27, 0x72, 0x57, 0x3d,
	0x89, 0xf3, 0xcb, 0xda, 0xdc, 0xe1, 0xc7, 0x9b, 0x1c, 0xdf, 0xbd, 0x40, 0x97, 0x75, 0x7c, 0x6f,
	0x39, 0x64, 0x07, 0xbd, 0xf9, 0x17, 0x00, 0x00, 0xff, 0xff, 0x36, 0xb6, 0xe7, 0x90, 0x25, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MastercardCurrencyServiceClient is the client API for MastercardCurrencyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MastercardCurrencyServiceClient interface {
	GetCurrencyConversion(ctx context.Context, in *MastercardCurrencyConversionRequest, opts ...grpc.CallOption) (*MastercardCurrencyConversionReply, error)
}

type mastercardCurrencyServiceClient struct {
	cc *grpc.ClientConn
}

func NewMastercardCurrencyServiceClient(cc *grpc.ClientConn) MastercardCurrencyServiceClient {
	return &mastercardCurrencyServiceClient{cc}
}

func (c *mastercardCurrencyServiceClient) GetCurrencyConversion(ctx context.Context, in *MastercardCurrencyConversionRequest, opts ...grpc.CallOption) (*MastercardCurrencyConversionReply, error) {
	out := new(MastercardCurrencyConversionReply)
	err := c.cc.Invoke(ctx, "/mastercard.MastercardCurrencyService/GetCurrencyConversion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MastercardCurrencyServiceServer is the server API for MastercardCurrencyService service.
type MastercardCurrencyServiceServer interface {
	GetCurrencyConversion(context.Context, *MastercardCurrencyConversionRequest) (*MastercardCurrencyConversionReply, error)
}

func RegisterMastercardCurrencyServiceServer(s *grpc.Server, srv MastercardCurrencyServiceServer) {
	s.RegisterService(&_MastercardCurrencyService_serviceDesc, srv)
}

func _MastercardCurrencyService_GetCurrencyConversion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MastercardCurrencyConversionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MastercardCurrencyServiceServer).GetCurrencyConversion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mastercard.MastercardCurrencyService/GetCurrencyConversion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MastercardCurrencyServiceServer).GetCurrencyConversion(ctx, req.(*MastercardCurrencyConversionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MastercardCurrencyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mastercard.MastercardCurrencyService",
	HandlerType: (*MastercardCurrencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrencyConversion",
			Handler:    _MastercardCurrencyService_GetCurrencyConversion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/currency-conversion.proto",
}
